"""Attack scenario test cases for goal hijack security testing."""

from .attack_scenarios import (
    AttackScenario,
    AttackVector,
    SeverityLevel,
    ExpectedBehavior,
    EMAIL_INJECTION_SCENARIO,
    CALENDAR_INJECTION_SCENARIO,
    WEB_CONTENT_INJECTION_SCENARIO,
    TOOL_REDIRECTION_SCENARIO,
    GOAL_LOCK_DRIFT_SCENARIO,
    ALL_SCENARIOS,
    # Obfuscated scenarios
    EMAIL_INJECTION_BASE64,
    WEB_CONTENT_UNICODE,
    CALENDAR_JSON_INJECTION,
    EMAIL_MARKDOWN_OBFUSCATION,
    TOOL_CONTEXT_INJECTION,
    GOAL_DRIFT_MULTI_STAGE,
    WEB_HTML_ENTITY_ENCODING,
    EMAIL_ROT13_OBFUSCATION,
    CALENDAR_INLINE_CONTEXT_MIX,
    WEB_WHITESPACE_STEGANOGRAPHY,
    OBFUSCATED_SCENARIOS,
    ALL_SCENARIOS_WITH_OBFUSCATION
)

__all__ = [
    'AttackScenario',
    'AttackVector',
    'SeverityLevel',
    'ExpectedBehavior',
    'EMAIL_INJECTION_SCENARIO',
    'CALENDAR_INJECTION_SCENARIO',
    'WEB_CONTENT_INJECTION_SCENARIO',
    'TOOL_REDIRECTION_SCENARIO',
    'GOAL_LOCK_DRIFT_SCENARIO',
    'ALL_SCENARIOS',
    # Obfuscated scenarios
    'EMAIL_INJECTION_BASE64',
    'WEB_CONTENT_UNICODE',
    'CALENDAR_JSON_INJECTION',
    'EMAIL_MARKDOWN_OBFUSCATION',
    'TOOL_CONTEXT_INJECTION',
    'GOAL_DRIFT_MULTI_STAGE',
    'WEB_HTML_ENTITY_ENCODING',
    'EMAIL_ROT13_OBFUSCATION',
    'CALENDAR_INLINE_CONTEXT_MIX',
    'WEB_WHITESPACE_STEGANOGRAPHY',
    'OBFUSCATED_SCENARIOS',
    'ALL_SCENARIOS_WITH_OBFUSCATION'
]
